language: node_js
node_js:
  - "4.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libcairo2-dev
      - libpango1.0-dev
      - libssl-dev
      - libjpeg62-dev
      - libgif-dev
before_script:
  - npm install
script:
  - npm run build
  - npm test
after_success:
  - npm run coveralls
